### ISSUE TITLE
Invoking artifact operation with no arguments

### ISSUE THREAD

**Issue by u473t8** [jacamo-lang/camel-cartago#3]
When I try to invoke operation without arguments, a route doesn't pass an observable property to an artifact. For example, when I have an agent code like this:
```
!start.

+!start
  <-  
      focus(someArtifact);
      doStuff;
  .

+value(X)
  <-
    .print(X);
  .
```
and a route like this
```
    <route id="simpleOP">
    <from uri="jacamo-artifact:someArtifact?operation=doStuff&amp;args=()"/>
    <setBody><simple>value(5)</simple></setBody>
    <to uri="jacamo-artifact:someArtifact"/>
    </route>
```
I receive following output (the last two lines)
```
[ArtifactConsumer] Operation invoked: doStuff /0 - ()
[ArtifactConsumer] Expected number of args: 1, got 1
```

But when I add a dummy argument to the operation, everything works as expected.

Agent
```
!start.

+!start
  <-  
      focus(someArtifact);
      doStuff(1);
  .

+value(X)
  <-
    .print(X);
  .
```
Route
```
    <route id="simpleOP">
    <from uri="jacamo-artifact:someArtifact?operation=doStuff&amp;args=(Arg)"/>
    <setBody><simple>value(5)</simple></setBody>
    <to uri="jacamo-artifact:someArtifact"/>
    </route>
```
Output (the last four lines)
```
[ArtifactConsumer] Operation invoked: doStuff /1 - (Arg)
[ArtifactProducer] Observable property added: value(5)[artifact_name(someArtifact),percept_type(obs_prop)]
[ArtifactConsumer] Processed successfully
[Agent] 5
```
Maybe I am doing something wrong, or maybe such behavior is intentional.

**Comment by u473t8** [comment]
An `[ArtifactConsumer] Expected number of args: 1, got 1` message occurs when comparing the expected and the given number of arguments in the `operate` method of ArtifactConsumer class.
This the code that is responsible for it:
```
if(arguments.length != args.length) {
    logger.warning("Expected number of args: " + args.length + ", got " + args.length);
    return ;
}
```

First, I think `args.length` is duplicated in the warning message, probably there should be something like
```
"Expected number of args: " + args.length + ", got " + arguments.length
```
Then it seems that args.length is equal to 1, despite I specify zero arity in consumer endpoint.

**Comment by u473t8** [comment]
The problem is in the split method, called in `ArtifactConsumer` constructor. It splits empty string to list with one empty string element.
```
this.args = endpoint.getArgs().substring(1, endpoint.getArgs().length() - 1).trim().replace(" ", "").split(",");
```
Maybe args array should be filtered, for example:
```
this.args = Arrays.stream(this.args).filter(s -> !s.isEmpty()).toArray(String[]::new);
```
As a workaround one can specify `args=(,)` option in a consumer endpoint.

**Comment by Sergio-PB** [comment]
Dear,
I apologize for the response delay.
Yes, you are correct, there was a mistake concerning the exact point you noted. It was fixed in the newest version.

Thank you for the notice.
